### ISSUE TITLE
[Question] Adding Hand landmarks detection?

### ISSUE THREAD

**Issue by muhammedakyuzlu** [liuyulvv/lvvi#2]
That is impressive work, I'm trying to do a similar thing with hand landmarks, you can see my in-progress work here [hand-landmarks-cpp](https://github.com/muhammedakyuzlu/hand-landmarks-cpp.git), 
The whole idea came because mediapipe doesn't support CMake, What I did is I took the models and tried to make them run directly without any need for mediapipe API, but I got stuck on the palm model outputs, I couldn't figure out how to convert the [1,2016,18]and [1,2016] outputs to bbox, I think you can help me in my way or you can explain to my you did it so I can do it in your way.

I have a Linux docker image containing OpenCV and TensorFlow lite libs, when I cloned your repo I couldn't make it run inside it, I realized that there are dependencies like OpenGL. I guess I don't need OpenGL for my hand landmarks detection

**Comment by liuyulvv** [comment]
@muhammedakyuzlu Thank you. This repository is is to visualize the face mesh of mediapipe. 

For hand landmark, if you want to directly access the processed image, it is very easy. If it is some other information, such as the coordinates of relevant points, you need to modify some mediapipe configuration, but I should be able to help you. So do you want mediapipe to give you processed images or other information that you can process yourself

**Comment by liuyulvv** [comment]
I didn't put the mediapipe dll into the project, so it can't run, I'm sorry, because I didn't expect anyone to use this project.

**Comment by muhammedakyuzlu** [comment]
I want to try both ways, First I want to access the mediapipe hand landmarks processed image and print the 21*3 landmarks

**Comment by muhammedakyuzlu** [comment]
> I didn't put the mediapipe dll into the project, so it can't run, I'm sorry, because I didn't expect anyone to use this pr

**Comment by muhammedakyuzlu** [comment]
I cloned your mediapipe repo including the DLL, how can I refer it inside my CMakeLists.txt and what is the API for hand landmarks

**Comment by liuyulvv** [comment]
@muhammedakyuzlu I will add hand landmarks support in my mediapipe repo in branch `mac` later. Because I don't have Linux, I can only test it in mac. I want them to be similar. I'll get back to you here when I'm done and tell you which files you need to copy to the executable directory. It should be done in a day

**Comment by muhammedakyuzlu** [comment]
@liuyulvv Thank you very much, when it's done I'll test it in Linux and confirm if it's working. 
I would love to help you with this process now and maybe we can support all mediapipe models and request a merge in the original repo. I believe that many developers would love seeing mediapipe supporting CMake

**Comment by liuyulvv** [comment]
@muhammedakyuzlu It can be obtained through `hand_only` branch of `lvvi` repo.

**Comment by muhammedakyuzlu** [comment]
@liuyulvv thanks a lot, I'll test it in my Linux environment and gives you feedback,

**Comment by muhammedakyuzlu** [comment]
Hello @liuyulvv, I managed to get the dynamic link library generated by the mediapipe compiled with the default settings. 
I didn't face the OpenCV and Clang problem yet but I'm getting a **graph AddPacketToInputStream failed** error with a black screen in outputBGRFrame. Any Idea what's causing this error? Thanks in advance.

**Comment by liuyulvv** [comment]
@muhammedakyuzlu Make sure that the `mediapipe` folder in the `bin` directory and the `hand_tracking_desktop_live.pbtxt` and the compiled `test_hand_track` are in the same directory. 

If it hadn't been caused by this, further debugging may have been required.

**Comment by muhammedakyuzlu** [comment]
@liuyulvv there is a mediapipe folder in the bin directory and these are the files

.
├── bazel-out
│   └── darwin_arm64-opt
│       └── bin
│           └── mediapipe
│               └── dll
│                   └── libmediapipe.so -> ../../../../../../lib/mac/libmediapipe.so
├── hand_tracking_desktop_live.pbtxt
├── mediapipe
│   └── modules
│       ├── hand_landmark
│       │   ├── BUILD
│       │   ├── calculators
│       │   │   ├── BUILD
│       │   │   └── hand_landmarks_to_rect_calculator.cc
│       │   ├── handedness.txt
│       │   ├── hand_landmark_cpu.pbtxt
│       │   ├── hand_landmark_full.tflite
│       │   ├── hand_landmark_gpu.pbtxt
│       │   ├── hand_landmark_landmarks_to_roi.pbtxt
│       │   ├── hand_landmark_lite.tflite
│       │   ├── hand_landmark_model_loader.pbtxt
│       │   ├── hand_landmark_tracking_cpu_image.pbtxt
│       │   ├── hand_landmark_tracking_cpu.pbtxt
│       │   ├── hand_landmark_tracking_gpu_image.pbtxt
│       │   ├── hand_landmark_tracking_gpu.pbtxt
│       │   ├── palm_detection_detection_to_roi.pbtxt
│       │   └── README.md
│       └── palm_detection
│           ├── BUILD
│           ├── palm_detection_cpu.pbtxt
│           ├── palm_detection_full.tflite
│           ├── palm_detection_gpu.pbtxt
│           ├── palm_detection_lite.tflite
│           ├── palm_detection_model_loader.pbtxt
│           └── README.md
├── Release
│   ├── hand_tracking_desktop_live.pbtxt
│   ├── mediapipe
│   │   └── modules
│   │       ├── hand_landmark
│   │       │   ├── BUILD
│   │       │   ├── calculators
│   │       │   │   ├── BUILD
│   │       │   │   └── hand_landmarks_to_rect_calculator.cc
│   │       │   ├── handedness.txt
│   │       │   ├── hand_landmark_cpu.pbtxt
│   │       │   ├── hand_landmark_full.tflite
│   │       │   ├── hand_landmark_gpu.pbtxt
│   │       │   ├── hand_landmark_landmarks_to_roi.pbtxt
│   │       │   ├── hand_landmark_lite.tflite
│   │       │   ├── hand_landmark_model_loader.pbtxt
│   │       │   ├── hand_landmark_tracking_cpu_image.pbtxt
│   │       │   ├── hand_landmark_tracking_cpu.pbtxt
│   │       │   ├── hand_landmark_tracking_gpu_image.pbtxt
│   │       │   ├── hand_landmark_tracking_gpu.pbtxt
│   │       │   ├── palm_detection_detection_to_roi.pbtxt
│   │       │   └── README.md
│   │       └── palm_detection
│   │           ├── BUILD
│   │           ├── palm_detection_cpu.pbtxt
│   │           ├── palm_detection_full.tflite
│   │           ├── palm_detection_gpu.pbtxt
│   │           ├── palm_detection_lite.tflite
│   │           ├── palm_detection_model_loader.pbtxt
│   │           └── README.md
│   ├── mediapipe.dll
│   ├── opencv_world3410.dll
│   └── test_hand_track.exe
└── test_hand_track

hand_tracking_desktop_live.pbtxt and the compiled test_hand_track are in the same directory.
I tracked the code till RET_CHECK(stream).SetNoLogging() << absl::Substitute(
        "AddPacketToInputStream called on input stream \"$0\" which is not a "
        "graph input stream.",  stream_name); in AddPacketToInputStreamInternal function

**Comment by liuyulvv** [comment]
@muhammedakyuzlu Please make sure that dynamic library was compiled with the code of the `dev` branch.

If the same problem persists, you can start debugging in [Detect](https://github.com/liuyulvv/mediapipe/blob/dev/mediapipe/dll/mediapipe_dll.cc#L31)

Log with `logger_->Log`

**Comment by muhammedakyuzlu** [comment]
@liuyulvv I couldn't figure out a way to make it run. instead, I tried using the models directly, here is my work 
https://github.com/muhammedakyuzlu/hand-landmarks-cpp.git  The main code is almost done thanks to https://github.com/terryky/tflite_gles_app.git , My code contain some bugs I'm trying to solve them beside the code now is very messy, I'll notify you ones it's bug-free

**Comment by muhammedakyuzlu** [comment]
@liuyulvv Hello again, I finished the code and now hand detection runs smoothly inside my c++ project. thanks again.
